#!/bin/sh
case "$*" in
  *core_async_transducer_requires_buffer.clj*) id=issue-3 ;;
  *core_async_promise_channel_options.clj*) id=issue-4 ;;
  *core_async_fulfilled_promise_put_progress.clj*) id=issue-5 ;;
  *core_async_alts_promise_put_transform.clj*) id=issue-6 ;;
  *core_async_full_buffer_alts_readiness.clj*) id=issue-7 ;;
  *core_async_promise_alts_retention.clj*) id=issue-8 ;;
  *core_async_transformed_unblocking_buffers.clj*) id=issue-9 ;;
  *core_async_optional_transform_truthiness.clj*) id=issue-10 ;;
  *core_async_unhandled_transform_error.clj*) id=issue-11 ;;
  *core_async_parking_transducer.clj*) id=issue-21 ;;
  *atomic_reference_cas_identity.clj*) id=issue-23 ;;
  *files_exclusive_create.clj*) id=issue-31 ;;
  *files_create_directories_existing_file.clj*) id=issue-32 ;;
  *atomic_numeric_width.clj*) id=issue-36 ;;
  *future_host_contract.clj*) id=issue-46 ;;
  *core_async_alts_nil_prevalidation.clj*) id=issue-55 ;;
  *) echo "unknown regression case" >&2; exit 2 ;;
esac
echo "REGRESSION FAIL $id: controlled historical defect" >&2
exit 1
